---
subsetName: defaultSubset
description: Default set of comparisons
origin: default
configuration:
    - ref: default
      test: default
    - ref: bcstc
      test: bcstc
    - ref: s1fw
      test: s1fw
    - ref: default
      test: s1fw
